export const moviesData = [
  {
    type: "Movie",
    name: "Cruella",
    src: "https://lumiere-a.akamaihd.net/v1/images/p_cruella_21672_ba40c762.jpeg",
    year: "2021",
    description:
      "Before she becomes Cruella de Vil, teenage Estella has a dream. She wishes to become a fashion designer, having been gifted with talent, innovation, and ambition all in equal measures. But life seems intent on making sure her dreams never come true. Having wound up penniless and orphaned in London at 12, 10 years later Estella runs wild through the city streets with her best friends and partners-in-(petty)-crime, Horace and Jasper, two amateur thieves. When a chance encounter vaults Estella into the world of the young rich and famous, however, she begins to question the existence she's built for herself in London and wonders whether she might, indeed, be destined for more after all.",
    director: "Craig Gillespie",
    cast: "Emma Thompson, Joel Fry, Paul Walter Hauser, John McCrea",
    rating: "7.4",
    language: "English",
    origin: "United States, United Kingdom",
    isWatched: "true",
    button: "Add to Watch List",
  },
  {
    type: "Movie",
    name: "Black Panther",
    src: "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_FMjpg_UX1000_.jpg",
    year: "2019",
    description:
      "Before she becomes Cruella de Vil, teenage Estella has a dream. She wishes to become a fashion designer, having been gifted with talent, innovation, and ambition all in equal measures. But life seems intent on making sure her dreams never come true. Having wound up penniless and orphaned in London at 12, 10 years later Estella runs wild through the city streets with her best friends and partners-in-(petty)-crime, Horace and Jasper, two amateur thieves. When a chance encounter vaults Estella into the world of the young rich and famous, however, she begins to question the existence she's built for herself in London and wonders whether she might, indeed, be destined for more after all.",
    director: "Craig Gillespie",
    cast: "Emma Thompson, Joel Fry, Paul Walter Hauser, John McCrea",
    rating: "7.4",
    language: "English",
    origin: "United States, United Kingdom",
    isWatched: "true",
    button: "Add to Watch List",
  },
  {
    type: "Movie",
    name: "Dumbo",
    src: "https://upload.wikimedia.org/wikipedia/en/thumb/9/91/Dumbo_%282019_film%29.png/220px-Dumbo_%282019_film%29.png",
    year: "2018",
    description:
      "Before she becomes Cruella de Vil, teenage Estella has a dream. She wishes to become a fashion designer, having been gifted with talent, innovation, and ambition all in equal measures. But life seems intent on making sure her dreams never come true. Having wound up penniless and orphaned in London at 12, 10 years later Estella runs wild through the city streets with her best friends and partners-in-(petty)-crime, Horace and Jasper, two amateur thieves. When a chance encounter vaults Estella into the world of the young rich and famous, however, she begins to question the existence she's built for herself in London and wonders whether she might, indeed, be destined for more after all.",
    director: "Craig Gillespie",
    cast: "Emma Thompson, Joel Fry, Paul Walter Hauser, John McCrea",
    rating: "7.4",
    language: "English",
    origin: "United States, United Kingdom",
    isWatched: "true",
    button: "Add to Watch List",
  },
  {
    type: "Movie",
    name: "House of Gucci",
    src: "https://mediafiles.cineplex.com/Central/Film/Posters/33049_320_470.jpg",
    year: "2021",
    description:
      "Before she becomes Cruella de Vil, teenage Estella has a dream. She wishes to become a fashion designer, having been gifted with talent, innovation, and ambition all in equal measures. But life seems intent on making sure her dreams never come true. Having wound up penniless and orphaned in London at 12, 10 years later Estella runs wild through the city streets with her best friends and partners-in-(petty)-crime, Horace and Jasper, two amateur thieves. When a chance encounter vaults Estella into the world of the young rich and famous, however, she begins to question the existence she's built for herself in London and wonders whether she might, indeed, be destined for more after all.",
    director: "Craig Gillespie",
    cast: "Emma Thompson, Joel Fry, Paul Walter Hauser, John McCrea",
    rating: "7.4",
    language: "English",
    origin: "United States, United Kingdom",
    isWatched: "true",
    button: "Add to Watch List",
  },
  {
    type: "Movie",
    name: "Harry Potter",
    src: "https://i5.walmartimages.com/asr/c2e6e7ca-1450-4be0-8857-871af845f21a.4cf3552a15663cb94216ab32a47c3659.jpeg",
    year: "2005",
    description:
      "Before she becomes Cruella de Vil, teenage Estella has a dream. She wishes to become a fashion designer, having been gifted with talent, innovation, and ambition all in equal measures. But life seems intent on making sure her dreams never come true. Having wound up penniless and orphaned in London at 12, 10 years later Estella runs wild through the city streets with her best friends and partners-in-(petty)-crime, Horace and Jasper, two amateur thieves. When a chance encounter vaults Estella into the world of the young rich and famous, however, she begins to question the existence she's built for herself in London and wonders whether she might, indeed, be destined for more after all.",
    director: "Craig Gillespie",
    cast: "Emma Thompson, Joel Fry, Paul Walter Hauser, John McCrea",
    rating: "7.4",
    language: "English",
    origin: "United States, United Kingdom",
    isWatched: "true",
    button: "Add to Watch List",
  },
  {
    type: "Movie",
    name: "Sing",
    src: "https://images-na.ssl-images-amazon.com/images/I/91napY3-NLL._RI_.jpg",
    year: "2010",
    description:
      "Before she becomes Cruella de Vil, teenage Estella has a dream. She wishes to become a fashion designer, having been gifted with talent, innovation, and ambition all in equal measures. But life seems intent on making sure her dreams never come true. Having wound up penniless and orphaned in London at 12, 10 years later Estella runs wild through the city streets with her best friends and partners-in-(petty)-crime, Horace and Jasper, two amateur thieves. When a chance encounter vaults Estella into the world of the young rich and famous, however, she begins to question the existence she's built for herself in London and wonders whether she might, indeed, be destined for more after all.",
    director: "Craig Gillespie",
    cast: "Emma Thompson, Joel Fry, Paul Walter Hauser, John McCrea",
    rating: "7.4",
    language: "English",
    origin: "United States, United Kingdom",
    isWatched: "true",
    button: "Add to Watch List",
  },
  {
    type: "Movie",
    name: "Spider-Man",
    src: "https://cdn.ebaumsworld.com/mediaFiles/picture/883100/86519706.jpg",
    year: "2012",
    description:
      "Before she becomes Cruella de Vil, teenage Estella has a dream. She wishes to become a fashion designer, having been gifted with talent, innovation, and ambition all in equal measures. But life seems intent on making sure her dreams never come true. Having wound up penniless and orphaned in London at 12, 10 years later Estella runs wild through the city streets with her best friends and partners-in-(petty)-crime, Horace and Jasper, two amateur thieves. When a chance encounter vaults Estella into the world of the young rich and famous, however, she begins to question the existence she's built for herself in London and wonders whether she might, indeed, be destined for more after all.",
    director: "Craig Gillespie",
    cast: "Emma Thompson, Joel Fry, Paul Walter Hauser, John McCrea",
    rating: "7.4",
    language: "English",
    origin: "United States, United Kingdom",
    isWatched: "true",
    button: "Add to Watch List",
  },
  {
    type: "Movie",
    name: "The Dark Night",
    src: "https://i.ebayimg.com/images/g/tTEAAOSwzRlZgWnw/s-l400.jpg",
    year: "2011",
    description:
      "Before she becomes Cruella de Vil, teenage Estella has a dream. She wishes to become a fashion designer, having been gifted with talent, innovation, and ambition all in equal measures. But life seems intent on making sure her dreams never come true. Having wound up penniless and orphaned in London at 12, 10 years later Estella runs wild through the city streets with her best friends and partners-in-(petty)-crime, Horace and Jasper, two amateur thieves. When a chance encounter vaults Estella into the world of the young rich and famous, however, she begins to question the existence she's built for herself in London and wonders whether she might, indeed, be destined for more after all.",
    director: "Craig Gillespie",
    cast: "Emma Thompson, Joel Fry, Paul Walter Hauser, John McCrea",
    rating: "7.4",
    language: "English",
    origin: "United States, United Kingdom",
    isWatched: "true",
    button: "Add to Watch List",
  },
];
